import { Router } from "express";
import auth from "../middlewares/auth";
import authRouter from "./auth";
import billRouter from "./bill";
import calenderRouter from "./calender";
import candidateRouter from "./candidate";
import categoryRouter from "./category";
import clientRouter from "./client";
import creditNotesRouter from "./creditNote";
import customerRouter from "./customer";
import dashboardRouter from "./dashboard";
import departmentRouter from "./department";
import emailRouter from "./email";
import employeeRouter from "./employee";
import expenseRouter from "./expense";
import goalRouter from "./goal";
import goalTypeRouter from "./goalType";
import holidayRouter from "./holiday";
import investmentRouter from "./investment";
import jobRouter from "./job";
import leadRouter from "./lead";
import leaveRouter from "./leave";
import leaveTypeRouter from "./leave-type";
import loanRouter from "./loan";
import locationRouter from "./location";
import overtimeRouter from "./overtime";
import policyRouter from "./policy";
import projectRouter from "./project";
import providentFundRouter from "./providentFund";
import roleRouter from "./role";
import saleEstimateRouter from "./saleEstimate";
import saleInvoiceRouter from "./saleInvoice";
import salePaymentRouter from "./salePayment";
import saleReportRouter from "./saleReport";
import taxRouter from "./tax";
import ticketsRouter from "./tickets";
import vendorRouter from "./vendor";
import vendorCreditRouter from "./vendorCredit";

const router = Router();

router.use("/auth", authRouter);
router.use("/project", auth, projectRouter);
router.use("/dashboard", auth, dashboardRouter);
router.use("/department", auth, departmentRouter);
router.use("/role", auth, roleRouter);
router.use("/employee", auth, employeeRouter);
router.use("/client", auth, clientRouter);
router.use("/location", auth, locationRouter);
router.use("/holiday", auth, holidayRouter);
router.use("/calendar", auth, calenderRouter);
router.use("/category", auth, categoryRouter);
router.use("/overtime", auth, overtimeRouter);
router.use("/leave-type", auth, leaveTypeRouter);
router.use("/investment", auth, investmentRouter);
router.use("/loan", auth, loanRouter);
router.use("/provident-fund", auth, providentFundRouter);
router.use("/tax", auth, taxRouter);
router.use("/job", jobRouter);
router.use("/candidate", candidateRouter);
router.use("/policy", auth, policyRouter);
router.use("/ticket", auth, ticketsRouter);
router.use("/goal-type", auth, goalTypeRouter);
router.use("/goal", auth, goalRouter);
router.use("/sale-estimate", auth, saleEstimateRouter);
router.use("/sale-invoice", auth, saleInvoiceRouter);
router.use("/sale-payment", auth, salePaymentRouter);
router.use("/lead", auth, leadRouter);
router.use("/customer", auth, customerRouter);
router.use("/credit-note", auth, creditNotesRouter);
router.use("/vendor", auth, vendorRouter);
router.use("/expense", auth, expenseRouter);
router.use("/vendor-credit", auth, vendorCreditRouter);
router.use("/email", auth, emailRouter);
router.use("/leave", auth, leaveRouter);
router.use("/report", auth, saleReportRouter);
router.use("/bill", auth, billRouter);
export default router;
